pipeline {
    environment {
        repository = "vlwli99/service-discovery"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_token')
        dockerImage = ''
    }

    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Project') {
            steps {
                dir("./server/service-discovery") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Build Image'){
            steps{
                script{
                    dockerImage = docker.build("${repository}:service-discovery-${BUILD_NUMBER}", "-f server/service-discovery/Dockerfile ./server/service-discovery")
                }
            }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_ID} --password-stdin"
                }
            }
        }

        stage('Push Image'){
            steps{
                script{
                    sh "docker push \${repository}:service-discovery-\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Image'){
            steps{
                script{
                    sh "docker rmi \${repository}:service-discovery-\${BUILD_NUMBER}"
                }
            }
        }

        stage("Garbage Collect") {
            steps {
                script {
                    sh "docker kill \$(docker ps -q --filter ancestor=\${repository}:service-discovery-\${BUILD_NUMBER})"
                    sh "docker system prune -af --volumes"
                }
            }
        }

        stage("Deploy"){
            steps{
                script{
                    sh "docker rm -f service-discovery || true"
                    sh "docker run -d -p 8761:8761 --name service-discovery \${repository}:service-discovery-\${BUILD_NUMBER}"
                }
            }
        }
    }
}
