pipeline {
    environment {
        repository = "vlwli99/config-service"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_token')
        dockerImage = ''
    }

    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Project') {
            steps {
                dir("./server/config-service") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Build Image'){
            steps{
                script{
                    dockerImage = docker.build("${repository}:config-service-${BUILD_NUMBER}", "-f server/config-service/Dockerfile ./server/config-service")
                }
            }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_ID} --password-stdin"
                }
            }
        }

        stage('Push Image'){
            steps{
                script{
                    sh "docker push \${repository}:config-service-\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Image'){
            steps{
                script{
                    sh "docker rmi \${repository}:config-service-\${BUILD_NUMBER}"
                }
            }
        }

        stage("Garbage Collect") {
            steps {
                script {
                    def containers = sh(script: "docker ps -q --filter ancestor=\${repository}:config-service-\${BUILD_NUMBER}", returnStdout: true).trim()
                    if (containers) {
                        sh "docker kill \${containers}"
                    }
                    sh "docker system prune -af --volumes"
                }
            }
        }

        stage("Deploy"){
            steps{
                script{
                    sh "docker rm -f config-service || true"
                    sh "docker run -d -p 8888:8888 --name config-service \${repository}:config-service-\${BUILD_NUMBER}"
                }
            }
        }
    }
}
