pipeline {
    environment {
        repository = "vlwli99/api-gateway"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_token')
        dockerImage = ''
    }

    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Project') {
            steps {
                dir("./server/api-gateway") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
                dir("./server/user") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Build Image'){
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps{
                script {
                    dir("./server/api-gateway") {
                        sh 'docker-compose -f docker-compose.yml build'
                    }
                }
            }
        }

        stage('DockerHub Login'){
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps{
                script{
                    sh "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_ID} --password-stdin"
                }
            }
        }

        stage('Push Image'){
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps{
                script{
                    dir("./server/api-gateway") {
                        sh 'docker-compose -f docker-compose.yml push'
                    }
                }
            }
        }

        stage('Clean Image'){
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps {
                script {
                    def imageNames = [
                        "vlwli99/api-gateway",
                        "vlwli99/user",
                        "api-gateway-redis-user",
                        "api-gateway-redis-gateway",
                        "api-gateway-rabbitmq"
                    ]

                    imageNames.each { imageName ->
                        def imageIds = sh(script: "docker images -q ${imageName}", returnStdout: true).trim().split()
                        imageIds.each { id ->
                            if (id) {
                                sh "docker rmi ${id} || true"
                            }
                        }
                    }

                    sh 'docker image prune -f --filter until=1h'
                }
            }
        }

        stage('Pull') {
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps {
                script {
                    dir("./server/api-gateway") {
                        sh "docker-compose pull"
                    }
                }
            }
        }

        stage("Down") {
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps {
                script {
                    dir("./server/api-gateway") {
                        echo "Attempting to bring down containers..."
                        sh "docker-compose down --remove-orphans --volumes || true"

                        echo "Forcing container stop and removal..."
                        sh "docker-compose rm -fsv || true"

                    }
                    echo "Cleaning up all unused Docker resources..."
                    sh "docker system prune -af --volumes"
                }
            }
        }

        stage("Up"){
            when {
                anyOf {
                    changeset "**/server/api-gateway/**"
                    changeset "**/server/user/**"
                }
            }
            steps{
                script{
                    dir("./server/api-gateway") {
                        sh "docker-compose up -d --build"
                    }
                }
            }
        }
    }
}
